export const types = Object.freeze({
  // Sync
  FORECAST_START_FETCHING: 'FORECAST_START_FETCHING',
  FORECAST_STOP_FETCHING: 'FORECAST_STOP_FETCHING',
  FORECAST_FILL: 'FORECAST_FILL',
  FORECAST_SET_FETCHING_ERROR: 'FORECAST_SET_FETCHING_ERROR',
  FORECAST_SET_SELECTED_DAY: 'FORECAST_SET_SELECTED_DAY',
  FORECAST_FILTER_DAYS: 'FORECAST_FILTER_DAYS',
  FORECAST_WEEK: 'FORECAST_WEEK',

  // Async
  FORECAST_FETCH_ASYNC: 'FORECAST_FETCH_ASYNC',
})
